### PR TITLE
generated translation values and module

### PR DESCRIPTION
**Pull request by Moro-Code**
resolves https://github.com/gcdevops/HRWhiteListing/issues/141

This PR seeks to add french translations for departments and job positions.

How to test 
- First completely wipe your local instance. I had to regenerate the csv's so that the id's do not have special characters 
- Import data as described in the readme 
- install the fr_CA language, make sure to have developer mode active and uncheck the override term setting as this causes an error for some reason 
- install the hr_translations. module

### CODE REVIEW

**Comment by gabrielcossette** [comment]
Works but a small bug:
Department name is still in English in column view (but ok in sidebar):
image
and user view (also Employee Information title not translated):
image
So they are translated but doesn't always display translated, weird.

**Comment by will0684** [comment]
Seems to work well 👍

**Comment by gabrielcossette** [comment]
You don't have the issue I had above @will0684?

Also, not sure if it's related to my issue above but in the database, complete_name is not the same as name?

image

**Comment by will0684** [comment]
I definitely have that issues as well, works well otherwise.

**Comment by will0684** [comment]
Fixed the issue, there were some double underscores on the id for the department column in the .po

I can push the changes up to this branch @Moro-Code @gabrielcossette

**Comment by will0684** [comment]
Sorry ignore that last message. Didn't work the way I thought.

**Comment by Moro-Code** [comment]
Going to close this PR for now as it will be made irrelevant by the internal data import

**Pull request closed without merging**
