### PR TITLE
Add Helpdesk module

### PR DESCRIPTION
**Pull request by gabrielcossette**
https://github.com/gcdevops/HRWhiteListing/issues/294

- A new **Support** menu is added in Employees section
- **Log note** is used at the bottom of tickets

**Users**
- Users must be added to **Helpdesk User** group (default on creation of users)
- Users can only see their own tickets in a List view (record rule)
- When users create tickets, they can specify a different email address

**Admins**
- Admin must be added to **Helpdesk Manager** group
- Kanban and List views

I believe there are no email notifications of new/updated tickets for both Admins and Users. We'll have to test that.

### CODE REVIEW

**Comment by gabrielcossette** [comment]
Email notifications indeed don't seem to be in this module. We can add them by borrowing from this other module for example: https://apps.odoo.com/apps/modules/12.0/website_support/

Will create an issue.

**Comment by gabrielcossette** [comment]
I added the email notifications:

- An email notification is sent to administrators when a new tickets is created (email addresses hardcoded for now)
- We reply to a ticket by clicking on the **Reply** button at the top of the ticket. Email is sent to User or Assigned Admin (depending on which replied) and the reply is added to the ticket log.
- We'll have to disable Email Notifications in the existing user profiles to avoid double email notifications. I changed the default configuration.
- When you test, you'll need to change this line with your email address before you install the module: https://github.com/gcdevops/OdooDocker/blob/957de3ce4befab64d0d112fa97ce3aa4b66a5cac/add-ons/helpdesk_lite/models/helpdesk_ticket.py#L190 And add an outgoing email server in Odoo's configuration (Settings->Technical->Email->Outgoing Mail Servers). I can share a test one, let me know.

**Comment by jaysonmc** [comment]
Requested by @gabrielcossette for another tester
@Moro-Code @var-kyle could you re-rest please?

**Comment by Moro-Code** [comment]
@jaysonmc testing now yes

**Comment by Moro-Code** [comment]
Hey, I added a field to the settings page that will set the admin email rather than needing to hardcode it 

Screen Shot 2020-05-15 at 3 54 25 PM

This needed to be added now since there seems to be some issue with inheriting ```res.company``` and adding fields after the module has been installed which is used to store configuration settings. To test this you're probably going to have to reinstall the helpdesk module as restarting the server doesn't work

**Comment by Moro-Code** [comment]
hey kyle do you mean adding an outgoing email server or setting the admin email through the settings field ?

**Comment by var-kyle** [comment]
Adding the email server. Setting an email address was fine in the settings, I just wasn't able to receive emails about tickets.

**Pull request merged**
