### PR TITLE
Add building type

### PR DESCRIPTION
**Pull request by e-wu**
https://github.com/gcdevops/HRWhiteListing/issues/311#event-3361526786

### CODE REVIEW

**Comment by e-wu** [comment]
Works for me :) and thanks

**Comment by Moro-Code** [comment]
I would have proposed we do this like we did for classifications, regions ect.

**Comment by e-wu** [comment]
Will do this in next release, so tomorrow? Since we releasing every day :)

**Comment by Moro-Code** [comment]
We have to take care about this in the future. This is not transient code that can be altered easily and reloaded. This is ORM code which means its mapped to the database. I should have blocked this PR but did not get a chance too. The field will be created in production as well now since we're going to have to leave it as it's merged to dev.

**Pull request merged**
