### PR TITLE
Improve FR translation

### PR DESCRIPTION
**Pull request by gabrielcossette**
https://github.com/gcdevops/HRWhiteListing/issues/307

**Note:** If you wish to test, you need to start from an empty database (unless you found a way to update existing translations, I haven't ;-)

### CODE REVIEW

**Comment by Moro-Code** [comment]
Not sure of the point of the PR if we can't update an existing DB. Unless we're planning to manage translations through this file is there really a point to it?

**Comment by gabrielcossette** [comment]
> Not sure if we need this PR since we can't update an existing DB. Unless we're planning to manage translations through this file is there really a point to it?

I would say it is still useful if we need to start an environment from scratch, and it keeps track of translated terms in case someone wants to review them.

Beside, it's just a few clicks to generate the file from prod, so very low effort.

**Comment by Moro-Code** [comment]
@jaysonmc 

> From the app perspective, more french terms the better

Looks like that can only be done from the UI at this point which is why I don't think this file is really useful at this point.   

@gabrielcossette 

> I would say it is still useful if we need to start an environment from scratch, and it keeps track of translated terms in case someone wants to review them.

I mean there is no harm in it which is why I didn't block it but at the same time we are never going to start an environment from scratch at this point. So we'll have to keep track of whether or not we have updated this file. I see your point about keeping track of translated terms though. Still, I would lean towards not adding files if there is not much of a use. However, you can go ahead and merge if you still think its useful.

**Comment by gabrielcossette** [comment]
Thanks for your feedback Omar, very good point. I'll merge because it can still be useful when we spin up a local dev environment with a blank database. However, it's not worth keeping the file fully up-to-date all the time.

**Pull request merged**
